import type { QuranSession } from '@/features/lib/types'
import { SEED_IDS } from '@/features/lib/seedIds'

export const SEED_QURAN_SESSIONS: QuranSession[] = [
  {
    id: 'quran_001',
    childId: SEED_IDS.adam,
    type: 'Revision',
    surah: 'Al-Mulk',
    fromAyah: 1,
    toAyah: 5,
    notes: '',
    date: '2026-05-01',
    lastLogged: '2 days ago',
  },
  {
    id: 'quran_002',
    childId: SEED_IDS.adam,
    type: 'Revision',
    surah: 'Al-Mulk',
    fromAyah: 1,
    toAyah: 5,
    notes: '',
    date: '2026-04-30',
    lastLogged: '3 days ago',
  },
  {
    id: 'quran_003',
    childId: SEED_IDS.adam,
    type: 'Recitation',
    surah: 'Al-Fatihah',
    fromAyah: 1,
    toAyah: 7,
    notes: 'Tajweed check',
    date: '2026-04-29',
    lastLogged: '4 days ago',
  },
  {
    id: 'quran_004',
    childId: SEED_IDS.khadijah,
    type: 'New memorization',
    surah: 'Al-Alaq',
    fromAyah: 1,
    toAyah: 3,
    notes: '',
    date: '2026-05-03',
    lastLogged: 'Today',
  },
  {
    id: 'quran_005',
    childId: SEED_IDS.khadijah,
    type: 'Revision',
    surah: 'Al-Ikhlas',
    fromAyah: 1,
    toAyah: 4,
    notes: '',
    date: '2026-05-02',
    lastLogged: 'Yesterday',
  },
  {
    id: 'quran_006',
    childId: SEED_IDS.khadijah,
    type: 'Recitation',
    surah: 'Al-Baqarah',
    fromAyah: 1,
    toAyah: 10,
    notes: '',
    date: '2026-05-01',
    lastLogged: '2 days ago',
  },
  {
    id: 'quran_007',
    childId: SEED_IDS.zayd,
    type: 'Recitation practice',
    surah: 'Juz 30',
    fromAyah: 1,
    toAyah: 50,
    notes: 'Full juz review',
    date: '2026-05-02',
    lastLogged: 'Yesterday',
  },
  {
    id: 'quran_008',
    childId: SEED_IDS.zayd,
    type: 'Revision',
    surah: 'Al-Mulk',
    fromAyah: 1,
    toAyah: 30,
    notes: '',
    date: '2026-05-01',
    lastLogged: '2 days ago',
  },
  {
    id: 'quran_009',
    childId: SEED_IDS.zayd,
    type: 'Recitation',
    surah: 'Juz 30',
    fromAyah: 1,
    toAyah: 50,
    notes: '',
    date: '2026-04-29',
    lastLogged: '4 days ago',
  },
  {
    id: 'quran_010',
    childId: SEED_IDS.adam,
    type: 'Recitation',
    surah: 'Al-Ikhlas',
    fromAyah: 1,
    toAyah: 4,
    notes: '',
    date: '2026-04-28',
    lastLogged: '5 days ago',
  },
  {
    id: 'quran_011',
    childId: SEED_IDS.khadijah,
    type: 'Revision',
    surah: 'Al-Ikhlas',
    fromAyah: 1,
    toAyah: 4,
    notes: '',
    date: '2026-04-27',
    lastLogged: '6 days ago',
  },
]
