import type { StudentProfile } from '@/features/lib/types'
import { SEED_IDS } from '@/features/lib/seedIds'

export const SEED_STUDENT_PROFILES: StudentProfile[] = [
  {
    id: SEED_IDS.layth,
    householdId: SEED_IDS.household,
    firstName: 'Layth',
    lastName: 'Al-Tayib',
    name: 'Layth Al-Tayib',
    gradeLabel: 'Grade 4',
    dob: '2015-09-01',
    username: 'layth',
    password: 'password',
    isActive: true,
    learnerLoginEnabled: true,
    avatarInitials: 'L',
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: SEED_IDS.hawa,
    householdId: SEED_IDS.household,
    firstName: 'Hawa',
    lastName: 'Al-Tayib',
    name: 'Hawa Al-Tayib',
    gradeLabel: 'Grade 1',
    dob: '2018-09-01',
    username: 'hawa',
    password: 'password',
    isActive: true,
    learnerLoginEnabled: true,
    avatarInitials: 'H',
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: SEED_IDS.talut,
    householdId: SEED_IDS.household,
    firstName: 'Talut',
    lastName: 'Al-Tayib',
    name: 'Talut Al-Tayib',
    gradeLabel: 'Grade 7',
    dob: '2012-09-01',
    username: 'talut',
    password: 'password',
    isActive: true,
    learnerLoginEnabled: true,
    avatarInitials: 'T',
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: SEED_IDS.samurai,
    householdId: SEED_IDS.household,
    firstName: 'Samurai',
    lastName: 'Al-Tayib',
    name: 'Samurai Al-Tayib',
    gradeLabel: 'Grade 4',
    dob: '2015-06-01',
    username: 'samurai',
    password: 'password',
    isActive: true,
    learnerLoginEnabled: true,
    avatarInitials: 'S',
    createdAt: '2026-01-01T00:00:00.000Z',
  },
]
