services:
  - type: web
    name: sheath-academy-dashboard
    runtime: node
    runtimeVersion: 22.22.2
    buildCommand: npm run build
    startCommand: npm run start
    envVars:
      - key: NPM_CONFIG_CACHE
        value: "/tmp/npm-cache"
      - key: TMPDIR
        value: "/tmp"
