import type { Resource } from '@/features/resources/types'
import { SEED_IDS } from '@/features/lib/seedIds'

export const SEED_RESOURCES: Resource[] = [
  {
    id: 'resource_seed_001',
    workspaceId: SEED_IDS.workspace,
    title: 'Math Mammoth Light Blue Grade 4',
    publisher: 'Math Mammoth',
    author: 'Maria Miller',
    edition: '2023',
    gradeLevel: '4',
    subjectCategory: 'Mathematics',
    resourceType: 'textbook',
    totalPages: 320,
    totalChapters: 8,
    verificationStatus: 'user-submitted',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'resource_seed_002',
    workspaceId: SEED_IDS.workspace,
    title: 'All About Reading Level 2',
    publisher: 'All About Learning Press',
    gradeLevel: '2',
    subjectCategory: 'Language Arts',
    resourceType: 'reader',
    totalPages: 180,
    totalLessons: 24,
    verificationStatus: 'verified',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'resource_seed_003',
    workspaceId: SEED_IDS.workspace,
    title: 'Khan Academy — Elementary Math',
    publisher: 'Khan Academy',
    subjectCategory: 'Mathematics',
    resourceType: 'online-course',
    totalLessons: 60,
    verificationStatus: 'user-submitted',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'resource_seed_004',
    workspaceId: SEED_IDS.workspace,
    title: "Quran with Tajweed — Hafs 'an 'Asim",
    subjectCategory: 'Islamic Studies',
    resourceType: 'quran-text',
    totalPages: 604,
    verificationStatus: 'verified',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'resource_seed_005',
    workspaceId: SEED_IDS.workspace,
    title: 'Story of the World Vol. 2: The Middle Ages',
    publisher: 'Peace Hill Press',
    author: 'Susan Wise Bauer',
    edition: 'Revised',
    gradeLevel: '5-8',
    subjectCategory: 'History',
    resourceType: 'textbook',
    totalPages: 360,
    totalChapters: 42,
    verificationStatus: 'user-submitted',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
]
