describe('WeeklyPlannerPage', () => {
  it('shows loading spinner while fetching household profile and lessons')
  it('shows error state when GET /api/household/profile fails')
  it('shows error state when GET /api/planner/lessons fails')
  it('renders week grid on desktop viewport once loaded')
  it('renders week list on mobile viewport once loaded')
  it('loads and displays lessons for the current week on mount')
  it('shows empty state when no lessons exist for the week')
  it('previous/next buttons navigate to previous/next week')
  it('date picker allows jumping to a specific week')
  it('jump-to-today button returns to current week')
  it('child filter shows only selected children's lessons')
  it('subject filter shows only selected subjects' lessons')
  it('combined filter (child + subject) shows correct intersection')
  it('all-children mode shows lessons for all children')
  it('weekends are rendered with de-emphasized styling')
})
